name: Replay
version: 1.0
main: com.terraboxstudios.replay.Main
depend:
  - ProtocolLib

commands:
  replay:
    description: Replay your surroundings
    usage: /replay <radius> <time_in_seconds> <speed>
    aliases:
      - instantreplay
      - ireplay
      - ir