name: InstantReplay
version: 2.0.0
author: Ben-D-Anderson
description: InstantReplay for Minecraft server administrators.
website: https://github.com/Ben-D-Anderson/InstantReplay
main: com.terraboxstudios.instantreplay.InstantReplay
api-version: 1.13

depend:
  - ProtocolLib

commands:
  replay:
    description: Replay your surroundings
    usage: /replay <radius> <time_in_seconds> <speed>
    aliases:
      - instantreplay