name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
main: com.terraboxstudios.instantreplay.InstantReplay

depend:
  - ProtocolLib

commands:
  replay:
    description: Replay your surroundings
    usage: /replay <radius> <time_in_seconds> <speed>
    aliases:
      - instantreplay